[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"

[workspace]
members = ["dnas/*/zomes/coordinator/*", "dnas/*/zomes/integrity/*", "lib/*"]

[workspace.dependencies]
hdi = "=0.4.0-beta-dev.5"
hdk = "=0.3.0-beta-dev.7"
holochain_integrity_types = "=0.3.0-beta-dev.5"
serde = "1"

[workspace.dependencies.demo]
path = "dnas/demo/zomes/coordinator/demo"

[workspace.dependencies.demo_integrity]
path = "dnas/demo/zomes/integrity/demo"

[workspace.dependencies.prefix_index]
path = "lib/prefix_index"
